// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf8c18z2FlyXkJ1nNsJW9vfTOkAzv_n6A',
    appId: '1:849517040817:web:a8e5555e9c3a4aa2dabe90',
    messagingSenderId: '849517040817',
    projectId: 'paycash-14e55',
    authDomain: 'paycash-14e55.firebaseapp.com',
    storageBucket: 'paycash-14e55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7TUrW2QCT6sVBB4kBDzejzPJEwpv7b4',
    appId: '1:849517040817:android:2a47f82fce32c257dabe90',
    messagingSenderId: '849517040817',
    projectId: 'paycash-14e55',
    storageBucket: 'paycash-14e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB3gO2N07QED1Z98zX4vGyJTEArQmW2U8',
    appId: '1:849517040817:ios:29eb9be00d4df397dabe90',
    messagingSenderId: '849517040817',
    projectId: 'paycash-14e55',
    storageBucket: 'paycash-14e55.firebasestorage.app',
    iosBundleId: 'com.example.paycash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB3gO2N07QED1Z98zX4vGyJTEArQmW2U8',
    appId: '1:849517040817:ios:29eb9be00d4df397dabe90',
    messagingSenderId: '849517040817',
    projectId: 'paycash-14e55',
    storageBucket: 'paycash-14e55.firebasestorage.app',
    iosBundleId: 'com.example.paycash',
  );
}
